services:
  - type: static
    name: portfolio-core-front
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
